"""
RepuestosPro - Bloque 16: Fiat Ducato, Jeep Wrangler, Gladiator, Renegade, Cherokee, Dodge Durango, Journey + Chrysler Pacifica, Kia Carnival, Ram 700
"""
import sqlite3, os

DB = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'db.sqlite')
ML = "https://listado.mercadolibre.cl/"
AZ = "https://www.amazon.com/s?k="

def ins(conn):
    c = conn.cursor()
    vehicles = {
        "fiat_ducato":{"name":"Fiat Ducato 2.3D MultiJet — 2014-2026","info":"F1A 2.3 MultiJet Diesel | Correa","crossNote":"= Peugeot Boxer, Citroen Jumper. Motor F1A FCA","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-30 diesel","details":"ACEA C3 | ~6.0L","brands":"Selenia WR, Shell Rimula, Motul","refs":[{"r":"5W-30 ACEA C3","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w30+fiat+ducato"},{"t":"Amazon","u":AZ+"Selenia+WR+5W-30"},{"t":"Selenia","u":"https://www.selenia.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite 2.3D","details":"MultiJet","brands":"MANN, UFI, Purflux","refs":[{"r":"MANN HU 718/1 n (verificar)","s":"verify"},{"r":"71749828 OEM (verificar)","s":"verify"}],"interval":"c/15-20k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+fiat+ducato"},{"t":"Amazon","u":AZ+"oil+filter+Fiat+Ducato"},{"t":"MANN","u":"https://www.mann-filter.com/"}]},{"cat":"Filtro Combustible","name":"Filtro petroleo","details":"Con separador agua","brands":"MANN, UFI, Bosch","refs":[{"r":"77367412 OEM (verificar)","s":"verify"}],"interval":"c/15-20k","links":[{"t":"MercadoLibre","u":ML+"filtro+combustible+fiat+ducato"},{"t":"Amazon","u":AZ+"fuel+filter+Fiat+Ducato"},{"t":"MANN","u":"https://www.mann-filter.com/"}]}],"Encendido":[{"cat":"Bujias Precal.","name":"Bujias precalentamiento x4","details":"Diesel","brands":"Bosch, NGK","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/80-100k","links":[{"t":"MercadoLibre","u":ML+"bujia+precalentamiento+fiat+ducato"},{"t":"Amazon","u":AZ+"glow+plug+Fiat+Ducato+2.3"},{"t":"Bosch","u":"https://www.boschautoparts.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"Disco ventilado ~300mm","brands":"TRW, Brembo, Bosch","refs":[{"r":"77364517 OEM (verificar)","s":"verify"}],"interval":"c/30-50k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+fiat+ducato"},{"t":"Amazon","u":AZ+"brake+pads+Fiat+Ducato"},{"t":"TRW","u":"https://www.trwaftermarket.com/"}]}],"Distribucion":[{"cat":"Correa","name":"Correa distribucion","details":"MultiJet correa c/120k","brands":"Gates, Dayco, Continental","refs":[{"r":"Correa 2.3D c/120k","s":"confirmed"}],"interval":"c/120k o 5 anos","links":[{"t":"MercadoLibre","u":ML+"kit+distribucion+fiat+ducato+2.3"},{"t":"Amazon","u":AZ+"timing+belt+Fiat+Ducato+2.3"},{"t":"Gates","u":"https://www.gates.com/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"215/70 R15C / 225/75 R16C","details":"Comercial","brands":"Michelin, Continental, Pirelli","refs":[{"r":"215/70 R15C","s":"confirmed"},{"r":"225/75 R16C","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+215+70+r15c"},{"t":"Michelin","u":"https://www.michelin.cl/"},{"t":"Continental","u":"https://www.continental-neumaticos.cl/"}]}]}},
        "jeep_wrangler":{"name":"Jeep Wrangler 3.6 V6 / 2.0T — 2014-2026","info":"Pentastar 3.6 V6 / 2.0T Hurricane | Cadena","crossNote":"Pentastar comp. Cherokee, Gladiator, Durango","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-20","details":"API SP | ~5.7L (V6)","brands":"Mopar, Mobil 1, Pennzoil","refs":[{"r":"5W-20 MS-6395 (V6)","s":"confirmed"},{"r":"5W-30 (2.0T)","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w20+jeep+wrangler"},{"t":"Amazon","u":AZ+"Mopar+5W-20"},{"t":"Mopar","u":"https://www.mopar.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite V6","details":"Pentastar 3.6","brands":"Mopar, MANN, Wix","refs":[{"r":"Mopar 68191349AC","s":"confirmed"},{"r":"MANN W 11 102 (verificar)","s":"verify"}],"interval":"c/8-12k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+jeep+wrangler"},{"t":"Amazon","u":AZ+"Mopar+68191349AC"},{"t":"MANN","u":"https://www.mann-filter.com/"}]}],"Encendido":[{"cat":"Bujias","name":"Bujias x6 (V6)","details":"Platinum/Iridium","brands":"NGK, Champion, Mopar","refs":[{"r":"Mopar SPLZFR5C11 (verificar)","s":"verify"}],"interval":"c/50-100k","links":[{"t":"MercadoLibre","u":ML+"bujia+jeep+wrangler"},{"t":"Amazon","u":AZ+"spark+plug+Jeep+Wrangler+3.6"},{"t":"NGK","u":"https://www.ngk.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"Disco ventilado grande","brands":"Mopar, Wagner, Brembo","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/40-60k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+jeep+wrangler"},{"t":"Amazon","u":AZ+"brake+pads+Jeep+Wrangler"},{"t":"Wagner","u":"https://www.wagnerbrake.com/"}]}],"Distribucion":[{"cat":"Cadena","name":"Cadena distribucion","details":"Pentastar/2.0T cadena","brands":"-","refs":[{"r":"Cadena Pentastar","s":"confirmed"}],"interval":"Tensores c/150k+","links":[{"t":"MercadoLibre","u":ML+"cadena+distribucion+jeep+wrangler"},{"t":"Amazon","u":AZ+"timing+chain+Pentastar+3.6"},{"t":"Mopar","u":"https://www.mopar.com/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"255/70 R18 / 285/70 R17","details":"Off-road","brands":"BFGoodrich, Goodyear, Nitto","refs":[{"r":"255/70 R18","s":"confirmed"},{"r":"285/70 R17 (Rubicon)","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+255+70+r18"},{"t":"BFGoodrich","u":"https://www.bfgoodrich.cl/"},{"t":"Goodyear","u":"https://www.goodyear.cl/"}]}]}},
        "jeep_gladiator":{"name":"Jeep Gladiator 3.6 V6 — 2020-2026","info":"Pentastar 3.6 V6 | Cadena","crossNote":"= Wrangler pickup. Mismo motor y tren","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-20 = Wrangler","details":"~5.7L","brands":"Mopar, Mobil 1","refs":[{"r":"5W-20 MS-6395","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w20+jeep"},{"t":"Amazon","u":AZ+"Mopar+5W-20"},{"t":"Mopar","u":"https://www.mopar.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite = Wrangler","details":"Pentastar","brands":"Mopar, MANN","refs":[{"r":"Mopar 68191349AC","s":"confirmed"}],"interval":"c/8-12k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+jeep+gladiator"},{"t":"Amazon","u":AZ+"oil+filter+Jeep+Gladiator"},{"t":"Mopar","u":"https://www.mopar.com/"}]}],"Encendido":[{"cat":"Bujias","name":"Bujias x6 = Wrangler","details":"Pentastar","brands":"NGK, Mopar","refs":[{"r":"Comp. Wrangler V6","s":"verify"}],"interval":"c/50-100k","links":[{"t":"MercadoLibre","u":ML+"bujia+jeep+gladiator"},{"t":"Amazon","u":AZ+"spark+plug+Jeep+Gladiator"},{"t":"NGK","u":"https://www.ngk.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"= Wrangler","brands":"Mopar, Wagner","refs":[{"r":"Comp. Wrangler","s":"verify"}],"interval":"c/40-60k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+jeep+gladiator"},{"t":"Amazon","u":AZ+"brake+pads+Jeep+Gladiator"},{"t":"Wagner","u":"https://www.wagnerbrake.com/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"255/70 R18 / 285/70 R17","details":"= Wrangler","brands":"BFGoodrich, Goodyear, Nitto","refs":[{"r":"255/70 R18","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+285+70+r17"},{"t":"BFGoodrich","u":"https://www.bfgoodrich.cl/"},{"t":"Goodyear","u":"https://www.goodyear.cl/"}]}]}},
        "jeep_renegade":{"name":"Jeep Renegade 1.3T/1.8 — 2015-2026","info":"Firefly 1.3T / E.torQ 1.8 | Cadena(1.3T)/Correa(1.8)","crossNote":"Plataforma SUSW = Fiat 500X. Motor Firefly = Fiat Pulse/Argo","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-30","details":"API SP | ~4.0L","brands":"Selenia, Mopar, Mobil","refs":[{"r":"5W-30 API SP","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w30+jeep+renegade"},{"t":"Amazon","u":AZ+"5W-30+Jeep+Renegade"},{"t":"Mopar","u":"https://www.mopar.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite","details":"Segun motor","brands":"MANN, Mopar, Tecfil","refs":[{"r":"Verificar segun motor","s":"verify"}],"interval":"c/10k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+jeep+renegade"},{"t":"Amazon","u":AZ+"oil+filter+Jeep+Renegade"},{"t":"MANN","u":"https://www.mann-filter.com/"}]}],"Encendido":[{"cat":"Bujias","name":"Bujias x3(1.3T)/x4(1.8)","details":"","brands":"NGK, Bosch","refs":[{"r":"Verificar segun motor","s":"verify"}],"interval":"c/30-60k","links":[{"t":"MercadoLibre","u":ML+"bujia+jeep+renegade"},{"t":"Amazon","u":AZ+"spark+plug+Jeep+Renegade"},{"t":"NGK","u":"https://www.ngk.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"Disco ventilado ~278mm","brands":"TRW, Brembo, Bosch","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/30-50k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+jeep+renegade"},{"t":"Amazon","u":AZ+"brake+pads+Jeep+Renegade"},{"t":"Brembo","u":"https://www.brembo.com/"}]}],"Distribucion":[{"cat":"Cadena/Correa","name":"Cadena (1.3T) / Correa (1.8)","details":"1.8 E.torQ: correa c/50-60k","brands":"Gates, Continental","refs":[{"r":"Cadena Firefly 1.3T","s":"confirmed"},{"r":"Correa E.torQ c/50-60k","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"distribucion+jeep+renegade"},{"t":"Amazon","u":AZ+"timing+belt+Jeep+Renegade"},{"t":"Gates","u":"https://www.gates.com/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"215/60 R17 / 225/55 R18","details":"SUV compacto","brands":"Pirelli, Continental, Bridgestone","refs":[{"r":"215/60 R17","s":"confirmed"},{"r":"225/55 R18","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+215+60+r17"},{"t":"Pirelli","u":"https://www.pirelli.com/"},{"t":"Continental","u":"https://www.continental-neumaticos.cl/"}]}]}},
        "jeep_cherokee":{"name":"Jeep Cherokee 2.4/3.2 V6 — 2014-2023","info":"Tigershark 2.4 / Pentastar 3.2 V6 | Cadena","crossNote":"Pentastar comp. Wrangler, Grand Cherokee","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-20","details":"API SN | 5.0-5.7L","brands":"Mopar, Mobil 1, Pennzoil","refs":[{"r":"5W-20 MS-6395","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w20+jeep+cherokee"},{"t":"Amazon","u":AZ+"Mopar+5W-20"},{"t":"Mopar","u":"https://www.mopar.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite","details":"Segun motor","brands":"Mopar, MANN, Wix","refs":[{"r":"Mopar 68191349AC (3.2)","s":"confirmed"},{"r":"Verificar 2.4","s":"verify"}],"interval":"c/8-12k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+jeep+cherokee"},{"t":"Amazon","u":AZ+"oil+filter+Jeep+Cherokee"},{"t":"Mopar","u":"https://www.mopar.com/"}]}],"Encendido":[{"cat":"Bujias","name":"Bujias x4/x6","details":"Segun motor","brands":"NGK, Mopar","refs":[{"r":"Verificar segun motor","s":"verify"}],"interval":"c/50-100k","links":[{"t":"MercadoLibre","u":ML+"bujia+jeep+cherokee"},{"t":"Amazon","u":AZ+"spark+plug+Jeep+Cherokee"},{"t":"NGK","u":"https://www.ngk.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"Disco ventilado","brands":"Mopar, Wagner, TRW","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/40-60k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+jeep+cherokee"},{"t":"Amazon","u":AZ+"brake+pads+Jeep+Cherokee"},{"t":"Wagner","u":"https://www.wagnerbrake.com/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"225/60 R18 / 245/50 R20","details":"SUV","brands":"Michelin, Continental, Pirelli","refs":[{"r":"225/60 R18","s":"confirmed"},{"r":"245/50 R20","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+225+60+r18"},{"t":"Michelin","u":"https://www.michelin.cl/"},{"t":"Continental","u":"https://www.continental-neumaticos.cl/"}]}]}},
        "dodge_durango":{"name":"Dodge Durango 3.6 V6 / 5.7 V8 — 2014-2026","info":"Pentastar 3.6 V6 / HEMI 5.7 V8 | Cadena","crossNote":"Plataforma WK2. Pentastar = Wrangler/Cherokee. HEMI = Ram","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-20","details":"API SP | 5.7-7.0L","brands":"Mopar, Mobil 1, Pennzoil","refs":[{"r":"5W-20 MS-6395","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w20+dodge+durango"},{"t":"Amazon","u":AZ+"Mopar+5W-20"},{"t":"Mopar","u":"https://www.mopar.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite","details":"Segun motor","brands":"Mopar, MANN, Wix","refs":[{"r":"Mopar 68191349AC (V6)","s":"confirmed"},{"r":"Mopar MO-899 (V8 verificar)","s":"verify"}],"interval":"c/8-12k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+dodge+durango"},{"t":"Amazon","u":AZ+"oil+filter+Dodge+Durango"},{"t":"Mopar","u":"https://www.mopar.com/"}]}],"Encendido":[{"cat":"Bujias","name":"Bujias x6/x8","details":"Pentastar/HEMI","brands":"NGK, Mopar, Champion","refs":[{"r":"Verificar segun motor","s":"verify"}],"interval":"c/50-100k","links":[{"t":"MercadoLibre","u":ML+"bujia+dodge+durango"},{"t":"Amazon","u":AZ+"spark+plug+Dodge+Durango"},{"t":"NGK","u":"https://www.ngk.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"Disco ventilado grande","brands":"Mopar, Wagner, Brembo","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/40-60k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+dodge+durango"},{"t":"Amazon","u":AZ+"brake+pads+Dodge+Durango"},{"t":"Wagner","u":"https://www.wagnerbrake.com/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"265/50 R20 / 295/45 R20","details":"SUV grande","brands":"Michelin, Pirelli, Continental","refs":[{"r":"265/50 R20","s":"confirmed"},{"r":"295/45 R20","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+265+50+r20"},{"t":"Michelin","u":"https://www.michelin.cl/"},{"t":"Pirelli","u":"https://www.pirelli.com/"}]}]}},
        "dodge_journey":{"name":"Dodge Journey 2.4/3.6 — 2014-2022","info":"Tigershark 2.4 / Pentastar 3.6 V6 | Cadena","crossNote":"Pentastar comp. Durango, Cherokee","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-20","details":"API SN | ~4.7-5.7L","brands":"Mopar, Mobil","refs":[{"r":"5W-20 MS-6395","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w20+dodge+journey"},{"t":"Amazon","u":AZ+"5W-20+Dodge+Journey"},{"t":"Mopar","u":"https://www.mopar.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite","details":"Segun motor","brands":"Mopar, MANN, Wix","refs":[{"r":"Mopar 4884899AC (2.4 verificar)","s":"verify"},{"r":"Mopar 68191349AC (3.6)","s":"confirmed"}],"interval":"c/8-12k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+dodge+journey"},{"t":"Amazon","u":AZ+"oil+filter+Dodge+Journey"},{"t":"Mopar","u":"https://www.mopar.com/"}]}],"Encendido":[{"cat":"Bujias","name":"Bujias x4/x6","details":"Segun motor","brands":"NGK, Mopar","refs":[{"r":"Verificar segun motor","s":"verify"}],"interval":"c/50-100k","links":[{"t":"MercadoLibre","u":ML+"bujia+dodge+journey"},{"t":"Amazon","u":AZ+"spark+plug+Dodge+Journey"},{"t":"NGK","u":"https://www.ngk.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"Disco ventilado ~302mm","brands":"Wagner, TRW, Mopar","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/40-60k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+dodge+journey"},{"t":"Amazon","u":AZ+"brake+pads+Dodge+Journey"},{"t":"Wagner","u":"https://www.wagnerbrake.com/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"225/55 R19","details":"","brands":"Continental, Pirelli, Bridgestone","refs":[{"r":"225/55 R19","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+225+55+r19"},{"t":"Continental","u":"https://www.continental-neumaticos.cl/"},{"t":"Pirelli","u":"https://www.pirelli.com/"}]}]}},
        "chrysler_pacifica":{"name":"Chrysler Pacifica 3.6 V6 — 2017-2026","info":"Pentastar 3.6 V6 | Cadena","crossNote":"Pentastar comp. Wrangler, Cherokee, Durango","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-20","details":"API SP | ~5.7L","brands":"Mopar, Mobil 1, Pennzoil","refs":[{"r":"5W-20 MS-6395","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w20+chrysler"},{"t":"Amazon","u":AZ+"Mopar+5W-20"},{"t":"Mopar","u":"https://www.mopar.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite V6","details":"Pentastar","brands":"Mopar, MANN","refs":[{"r":"Mopar 68191349AC","s":"confirmed"}],"interval":"c/8-12k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+chrysler+pacifica"},{"t":"Amazon","u":AZ+"oil+filter+Chrysler+Pacifica"},{"t":"Mopar","u":"https://www.mopar.com/"}]}],"Encendido":[{"cat":"Bujias","name":"Bujias x6","details":"Pentastar","brands":"NGK, Mopar","refs":[{"r":"Comp. Wrangler V6","s":"verify"}],"interval":"c/50-100k","links":[{"t":"MercadoLibre","u":ML+"bujia+chrysler+pacifica"},{"t":"Amazon","u":AZ+"spark+plug+Chrysler+Pacifica"},{"t":"NGK","u":"https://www.ngk.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"Disco ventilado","brands":"Mopar, Wagner","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/40-60k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+chrysler+pacifica"},{"t":"Amazon","u":AZ+"brake+pads+Chrysler+Pacifica"},{"t":"Wagner","u":"https://www.wagnerbrake.com/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"235/60 R18 / 235/50 R20","details":"Minivan","brands":"Michelin, Continental, Bridgestone","refs":[{"r":"235/60 R18","s":"confirmed"},{"r":"235/50 R20","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+235+60+r18"},{"t":"Michelin","u":"https://www.michelin.cl/"},{"t":"Continental","u":"https://www.continental-neumaticos.cl/"}]}]}},
        "kia_carnival":{"name":"Kia Carnival 2.2D/3.5 V6 — 2015-2026","info":"D4HB 2.2 CRDi / G6DB 3.5 V6 | Cadena","crossNote":"= Sedona. 2.2D comp. Sorento. V6 comp. Mohave","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-30","details":"API SP / ACEA C3 | 5.5-6.0L","brands":"Kixx, Shell, Castrol","refs":[{"r":"5W-30 API SP","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w30+kia+carnival"},{"t":"Amazon","u":AZ+"5W-30+Kia+Carnival"},{"t":"Kixx","u":"https://www.kixxoil.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite","details":"Segun motor","brands":"Mobis, MANN, Bosch","refs":[{"r":"26320-2F100 (2.2D verificar)","s":"verify"},{"r":"MANN W 811/80 (V6)","s":"confirmed"}],"interval":"c/10-15k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+kia+carnival"},{"t":"Amazon","u":AZ+"oil+filter+Kia+Carnival"},{"t":"MANN","u":"https://www.mann-filter.com/"}]}],"Encendido":[{"cat":"Bujias","name":"Bujias x6 (V6) / Precal (diesel)","details":"Segun motor","brands":"NGK, Bosch, Mobis","refs":[{"r":"Verificar segun motor","s":"verify"}],"interval":"c/30-60k","links":[{"t":"MercadoLibre","u":ML+"bujia+kia+carnival"},{"t":"Amazon","u":AZ+"spark+plug+Kia+Carnival"},{"t":"NGK","u":"https://www.ngk.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"Disco ventilado ~320mm","brands":"Mobis, TRW, Brembo","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/30-50k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+kia+carnival"},{"t":"Amazon","u":AZ+"brake+pads+Kia+Carnival"},{"t":"TRW","u":"https://www.trwaftermarket.com/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"235/60 R18 / 235/55 R19","details":"Minivan grande","brands":"Michelin, Kumho, Continental","refs":[{"r":"235/60 R18","s":"confirmed"},{"r":"235/55 R19","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+235+60+r18"},{"t":"Michelin","u":"https://www.michelin.cl/"},{"t":"Kumho","u":"https://www.kumhotire.com/"}]}]}},
        "ram_700":{"name":"Ram 700 1.6 — 2015-2026","info":"Fiat E.torQ 1.6 | Correa","crossNote":"= Fiat Strada/Mobi base. Motor E.torQ FCA","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-30","details":"API SN | ~3.5L","brands":"Selenia, Mopar, Shell","refs":[{"r":"5W-30 API SN","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w30+ram+700"},{"t":"Amazon","u":AZ+"5W-30+Ram+700"},{"t":"Mopar","u":"https://www.mopar.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite E.torQ","details":"1.6 Fiat","brands":"MANN, Tecfil, Mopar","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/10k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+ram+700"},{"t":"Amazon","u":AZ+"oil+filter+Ram+700"},{"t":"MANN","u":"https://www.mann-filter.com/"}]}],"Encendido":[{"cat":"Bujias","name":"Bujias x4","details":"E.torQ","brands":"NGK, Bosch","refs":[{"r":"Comp. Fiat Strada","s":"verify"}],"interval":"c/30k","links":[{"t":"MercadoLibre","u":ML+"bujia+ram+700"},{"t":"Amazon","u":AZ+"spark+plug+Ram+700"},{"t":"NGK","u":"https://www.ngk.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"Disco solido ~240mm","brands":"TRW, Bosch","refs":[{"r":"Comp. Fiat Strada","s":"verify"}],"interval":"c/30-50k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+ram+700"},{"t":"Amazon","u":AZ+"brake+pads+Ram+700"},{"t":"Bosch","u":"https://www.boschautoparts.com/"}]}],"Distribucion":[{"cat":"Correa","name":"Correa distribucion","details":"E.torQ correa c/50-60k","brands":"Gates, Dayco","refs":[{"r":"Correa E.torQ c/50-60k","s":"confirmed"}],"interval":"c/50-60k","links":[{"t":"MercadoLibre","u":ML+"kit+distribucion+ram+700"},{"t":"Amazon","u":AZ+"timing+belt+Fiat+E.torQ"},{"t":"Gates","u":"https://www.gates.com/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"175/70 R14 / 185/65 R15","details":"Pickup compacta","brands":"Pirelli, Continental, Firestone","refs":[{"r":"175/70 R14","s":"confirmed"},{"r":"185/65 R15","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+175+70+r14"},{"t":"Pirelli","u":"https://www.pirelli.com/"},{"t":"Continental","u":"https://www.continental-neumaticos.cl/"}]}]}}
    }

    for vid, vdata in vehicles.items():
        c.execute("INSERT OR IGNORE INTO vehicles VALUES (?,?,?,?)", (vid, vdata["name"], vdata["info"], vdata["crossNote"]))
        order = 0
        for cat_name, parts in vdata["categories"].items():
            order += 1
            c.execute("INSERT INTO categories (vehicle_id, name, sort_order) VALUES (?,?,?)", (vid, cat_name, order))
            cat_id = c.lastrowid
            for p in parts:
                c.execute("INSERT INTO parts (category_id, cat_label, name, details, brands, interval_info) VALUES (?,?,?,?,?,?)",
                          (cat_id, p.get("cat",""), p["name"], p.get("details",""), p.get("brands",""), p.get("interval",None)))
                pid = c.lastrowid
                for r in p.get("refs",[]):
                    c.execute("INSERT INTO part_refs (part_id, reference, status) VALUES (?,?,?)", (pid, r["r"], r["s"]))
                for l in p.get("links",[]):
                    c.execute("INSERT INTO part_links (part_id, label, url) VALUES (?,?,?)", (pid, l["t"], l["u"]))
    conn.commit()
    total = c.execute("SELECT COUNT(*) FROM vehicles").fetchone()[0]
    parts_count = c.execute("SELECT COUNT(*) FROM parts").fetchone()[0]
    print(f"Bloque 16 insertado OK")
    print(f"Vehiculos totales: {total} | Componentes totales: {parts_count}")

if __name__ == "__main__":
    conn = sqlite3.connect(DB)
    conn.execute("PRAGMA foreign_keys = ON")
    ins(conn)
    conn.close()
