"""
RepuestosPro - Bloque 15: Renault Captur, Arkana, Oroch, Koleos, Alaskan, Megane + Fiat Mobi, Argo, Cronos, Pulse
"""
import sqlite3, os

DB = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'db.sqlite')
ML = "https://listado.mercadolibre.cl/"
AZ = "https://www.amazon.com/s?k="

def ins(conn):
    c = conn.cursor()
    vehicles = {
        "renault_captur":{"name":"Renault Captur 1.3T/1.6/2.0 — 2017-2026","info":"H5Ht 1.3 TCe / H4M 2.0 / HR16 1.6 | Cadena","crossNote":"Plataforma CMF-B. 1.3T comp. Arkana, Duster. HR16 = Nissan","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-30 RN0720","details":"ACEA C3 | ~4.5L","brands":"Elf Evolution, Motul, Castrol","refs":[{"r":"5W-30 RN0720/RN17","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w30+renault+elf"},{"t":"Amazon","u":AZ+"Elf+Evolution+5W-30"},{"t":"Elf","u":"https://www.elf.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite","details":"Segun motor","brands":"MANN, Purflux, Mahle","refs":[{"r":"152093920R OEM (1.3T verificar)","s":"verify"},{"r":"MANN W 7032 (verificar)","s":"verify"}],"interval":"c/10-15k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+renault+captur"},{"t":"Amazon","u":AZ+"oil+filter+Renault+Captur"},{"t":"MANN","u":"https://www.mann-filter.com/"}]}],"Encendido":[{"cat":"Bujias","name":"Bujias x4","details":"TCe Iridium","brands":"NGK, Bosch, Denso","refs":[{"r":"Verificar segun motor","s":"verify"}],"interval":"c/30-60k","links":[{"t":"MercadoLibre","u":ML+"bujia+renault+captur"},{"t":"Amazon","u":AZ+"spark+plug+Renault+Captur"},{"t":"NGK","u":"https://www.ngk.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"Disco ventilado ~280mm","brands":"TRW, Bosch, Brembo","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/30-50k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+renault+captur"},{"t":"Amazon","u":AZ+"brake+pads+Renault+Captur"},{"t":"TRW","u":"https://www.trwaftermarket.com/"}]}],"Distribucion":[{"cat":"Cadena","name":"Cadena distribucion","details":"TCe/H4M cadena","brands":"-","refs":[{"r":"Cadena 1.3T/2.0","s":"confirmed"}],"interval":"Tensores c/100-150k","links":[{"t":"MercadoLibre","u":ML+"cadena+distribucion+renault+captur"},{"t":"Amazon","u":AZ+"timing+chain+Renault+Captur"},{"t":"Renault","u":"https://www.renault.cl/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"215/60 R17 / 205/65 R16","details":"","brands":"Michelin, Continental, Pirelli","refs":[{"r":"215/60 R17","s":"confirmed"},{"r":"205/65 R16","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+215+60+r17"},{"t":"Michelin","u":"https://www.michelin.cl/"},{"t":"Continental","u":"https://www.continental-neumaticos.cl/"}]}]}},
        "renault_arkana":{"name":"Renault Arkana 1.3 TCe — 2021-2026","info":"H5Ht 1.3 TCe 160hp | Cadena","crossNote":"Plataforma CMF-B. Motor = Captur 1.3T, Duster 1.3T","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-30 RN0720","details":"ACEA C3 | ~4.5L","brands":"Elf, Motul, Castrol","refs":[{"r":"5W-30 RN0720","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w30+renault+elf"},{"t":"Amazon","u":AZ+"Elf+Evolution+5W-30"},{"t":"Elf","u":"https://www.elf.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite 1.3T","details":"= Captur 1.3T","brands":"MANN, Purflux","refs":[{"r":"Comp. Captur 1.3T","s":"verify"}],"interval":"c/10-15k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+renault+arkana"},{"t":"Amazon","u":AZ+"oil+filter+Renault+Arkana"},{"t":"MANN","u":"https://www.mann-filter.com/"}]}],"Encendido":[{"cat":"Bujias","name":"Bujias x4","details":"TCe Iridium","brands":"NGK, Bosch","refs":[{"r":"Comp. Captur 1.3T","s":"verify"}],"interval":"c/30-60k","links":[{"t":"MercadoLibre","u":ML+"bujia+renault+arkana"},{"t":"Amazon","u":AZ+"spark+plug+Renault+Arkana"},{"t":"NGK","u":"https://www.ngk.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"Disco ventilado ~300mm","brands":"TRW, Brembo","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/30-50k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+renault+arkana"},{"t":"Amazon","u":AZ+"brake+pads+Renault+Arkana"},{"t":"TRW","u":"https://www.trwaftermarket.com/"}]}],"Distribucion":[{"cat":"Cadena","name":"Cadena distribucion","details":"1.3T","brands":"-","refs":[{"r":"Cadena H5Ht","s":"confirmed"}],"interval":"Tensores c/100-150k","links":[{"t":"MercadoLibre","u":ML+"cadena+distribucion+renault+arkana"},{"t":"Amazon","u":AZ+"timing+chain+Renault+1.3+TCe"},{"t":"Renault","u":"https://www.renault.cl/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"215/55 R18","details":"","brands":"Michelin, Continental, Hankook","refs":[{"r":"215/55 R18","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+215+55+r18"},{"t":"Michelin","u":"https://www.michelin.cl/"},{"t":"Continental","u":"https://www.continental-neumaticos.cl/"}]}]}},
        "renault_oroch":{"name":"Renault Oroch 1.6/2.0 — 2016-2026","info":"H4M 2.0 / K4M 1.6 | Cadena(2.0)/Correa(1.6)","crossNote":"= Duster pickup. Motor H4M = Nissan MR20","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-30","details":"API SN | ~4.5L","brands":"Elf, Mobil, Shell","refs":[{"r":"5W-30 RN0700","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w30+renault"},{"t":"Amazon","u":AZ+"Elf+Evolution+5W-30"},{"t":"Elf","u":"https://www.elf.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite","details":"= Duster","brands":"MANN, Purflux, Mahle","refs":[{"r":"MANN W 75/3","s":"confirmed"},{"r":"8200768927 OEM (verificar)","s":"verify"}],"interval":"c/10-15k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+renault+oroch"},{"t":"Amazon","u":AZ+"oil+filter+Renault+Duster"},{"t":"MANN","u":"https://www.mann-filter.com/"}]}],"Encendido":[{"cat":"Bujias","name":"Bujias x4","details":"","brands":"NGK, Bosch","refs":[{"r":"Comp. Duster","s":"verify"}],"interval":"c/30k","links":[{"t":"MercadoLibre","u":ML+"bujia+renault+oroch"},{"t":"Amazon","u":AZ+"spark+plug+Renault+Oroch"},{"t":"NGK","u":"https://www.ngk.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"= Duster","brands":"TRW, Bosch","refs":[{"r":"Comp. Duster","s":"verify"}],"interval":"c/30-50k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+renault+oroch"},{"t":"Amazon","u":AZ+"brake+pads+Renault+Oroch"},{"t":"TRW","u":"https://www.trwaftermarket.com/"}]}],"Distribucion":[{"cat":"Cadena/Correa","name":"Cadena (2.0) / Correa (1.6)","details":"1.6 K4M: correa c/60k","brands":"Gates, Continental","refs":[{"r":"Cadena H4M 2.0","s":"confirmed"},{"r":"Correa K4M c/60k","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"distribucion+renault+oroch"},{"t":"Amazon","u":AZ+"timing+belt+Renault+K4M"},{"t":"Gates","u":"https://www.gates.com/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"215/65 R16","details":"Pickup","brands":"Continental, BFGoodrich, Pirelli","refs":[{"r":"215/65 R16","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+215+65+r16"},{"t":"Continental","u":"https://www.continental-neumaticos.cl/"},{"t":"BFGoodrich","u":"https://www.bfgoodrich.cl/"}]}]}},
        "renault_koleos":{"name":"Renault Koleos 2.5/2.0D — 2017-2026","info":"QR25DE 2.5 Nissan / M9R 2.0D | Cadena","crossNote":"Plataforma CMF-C/D = Nissan X-Trail. Motor QR25 = X-Trail","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-30","details":"API SN | ~4.6L","brands":"Elf, Mobil, Castrol","refs":[{"r":"5W-30 RN0720","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w30+renault"},{"t":"Amazon","u":AZ+"5W-30+Renault"},{"t":"Elf","u":"https://www.elf.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite QR25","details":"= Nissan X-Trail","brands":"MANN, Nissan, Wix","refs":[{"r":"15208-65F0E (Nissan)","s":"confirmed"},{"r":"MANN W 67/1","s":"confirmed"}],"interval":"c/10-15k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+renault+koleos"},{"t":"Amazon","u":AZ+"oil+filter+Renault+Koleos"},{"t":"MANN","u":"https://www.mann-filter.com/"}]}],"Encendido":[{"cat":"Bujias","name":"Bujias x4 (2.5)","details":"Iridium QR25","brands":"NGK, Denso","refs":[{"r":"LZKAR6AP-11 (comp. Nissan)","s":"confirmed"}],"interval":"c/30-60k","links":[{"t":"MercadoLibre","u":ML+"bujia+renault+koleos"},{"t":"Amazon","u":AZ+"spark+plug+Renault+Koleos"},{"t":"NGK","u":"https://www.ngk.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"Disco ventilado ~320mm","brands":"TRW, Brembo, Bosch","refs":[{"r":"Comp. X-Trail (verificar)","s":"verify"}],"interval":"c/30-50k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+renault+koleos"},{"t":"Amazon","u":AZ+"brake+pads+Renault+Koleos"},{"t":"TRW","u":"https://www.trwaftermarket.com/"}]}],"Distribucion":[{"cat":"Cadena","name":"Cadena distribucion","details":"QR25 cadena","brands":"-","refs":[{"r":"Cadena QR25DE","s":"confirmed"}],"interval":"Tensores c/150k+","links":[{"t":"MercadoLibre","u":ML+"cadena+distribucion+renault+koleos"},{"t":"Amazon","u":AZ+"timing+chain+Nissan+QR25"},{"t":"Renault","u":"https://www.renault.cl/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"225/60 R18 / 225/55 R19","details":"SUV","brands":"Michelin, Continental, Pirelli","refs":[{"r":"225/60 R18","s":"confirmed"},{"r":"225/55 R19","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+225+60+r18"},{"t":"Michelin","u":"https://www.michelin.cl/"},{"t":"Continental","u":"https://www.continental-neumaticos.cl/"}]}]}},
        "renault_alaskan":{"name":"Renault Alaskan 2.3D — 2017-2026","info":"M9T 2.3 dCi Biturbo Diesel | Cadena","crossNote":"= Nissan Navara/NP300. Motor M9T Renault","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-30 diesel","details":"ACEA C4 | ~6.5L","brands":"Elf Solaris, Shell Rimula","refs":[{"r":"5W-30 ACEA C4 RN0720","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w30+diesel+renault"},{"t":"Amazon","u":AZ+"Elf+Solaris+5W-30"},{"t":"Elf","u":"https://www.elf.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite 2.3D","details":"M9T","brands":"MANN, Purflux","refs":[{"r":"152095084R OEM (verificar)","s":"verify"}],"interval":"c/10-15k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+renault+alaskan"},{"t":"Amazon","u":AZ+"oil+filter+Renault+Alaskan"},{"t":"MANN","u":"https://www.mann-filter.com/"}]},{"cat":"Filtro Combustible","name":"Filtro petroleo","details":"Diesel con separador","brands":"MANN, Purflux, Bosch","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/10-20k","links":[{"t":"MercadoLibre","u":ML+"filtro+combustible+renault+alaskan"},{"t":"Amazon","u":AZ+"fuel+filter+Renault+Alaskan"},{"t":"MANN","u":"https://www.mann-filter.com/"}]}],"Encendido":[{"cat":"Bujias Precal.","name":"Bujias precalentamiento x4","details":"Diesel","brands":"Bosch, NGK","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/80-100k","links":[{"t":"MercadoLibre","u":ML+"bujia+precalentamiento+renault+alaskan"},{"t":"Amazon","u":AZ+"glow+plug+Renault+2.3+dCi"},{"t":"Bosch","u":"https://www.boschautoparts.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"Disco ventilado ~296mm","brands":"TRW, Bosch, Brembo","refs":[{"r":"Comp. Navara (verificar)","s":"verify"}],"interval":"c/30-50k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+renault+alaskan"},{"t":"Amazon","u":AZ+"brake+pads+Nissan+Navara"},{"t":"TRW","u":"https://www.trwaftermarket.com/"}]}],"Distribucion":[{"cat":"Cadena","name":"Cadena distribucion","details":"M9T cadena","brands":"-","refs":[{"r":"Cadena M9T","s":"confirmed"}],"interval":"Tensores c/150k+","links":[{"t":"MercadoLibre","u":ML+"cadena+distribucion+renault+alaskan"},{"t":"Amazon","u":AZ+"timing+chain+Renault+2.3+dCi"},{"t":"Renault","u":"https://www.renault.cl/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"255/60 R18","details":"Pickup","brands":"BFGoodrich, Continental, Bridgestone","refs":[{"r":"255/60 R18","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+255+60+r18"},{"t":"BFGoodrich","u":"https://www.bfgoodrich.cl/"},{"t":"Continental","u":"https://www.continental-neumaticos.cl/"}]}]}},
        "renault_megane":{"name":"Renault Megane 1.6/2.0/1.3T — 2010-2024","info":"K4M 1.6 / F4R 2.0 / H5Ht 1.3T | Correa(K4M)/Cadena(otros)","crossNote":"K4M comp. Fluence, Duster 1.6. 1.3T = Captur/Arkana","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-30/5W-40","details":"RN0700/0720 | ~4.5L","brands":"Elf, Motul, Castrol","refs":[{"r":"5W-30 RN0700 (1.6)","s":"confirmed"},{"r":"5W-40 RN0720 (2.0/1.3T)","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w30+renault+elf"},{"t":"Amazon","u":AZ+"Elf+Evolution+5W-30"},{"t":"Elf","u":"https://www.elf.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite","details":"Segun motor","brands":"MANN, Purflux","refs":[{"r":"MANN W 75/3 (K4M)","s":"confirmed"},{"r":"152093920R (1.3T verificar)","s":"verify"}],"interval":"c/10-15k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+renault+megane"},{"t":"Amazon","u":AZ+"oil+filter+Renault+Megane"},{"t":"MANN","u":"https://www.mann-filter.com/"}]}],"Encendido":[{"cat":"Bujias","name":"Bujias x4","details":"","brands":"NGK, Bosch","refs":[{"r":"Verificar segun motor","s":"verify"}],"interval":"c/30k","links":[{"t":"MercadoLibre","u":ML+"bujia+renault+megane"},{"t":"Amazon","u":AZ+"spark+plug+Renault+Megane"},{"t":"NGK","u":"https://www.ngk.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"Disco ventilado ~280mm","brands":"TRW, Bosch","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/30-50k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+renault+megane"},{"t":"Amazon","u":AZ+"brake+pads+Renault+Megane"},{"t":"TRW","u":"https://www.trwaftermarket.com/"}]}],"Distribucion":[{"cat":"Correa/Cadena","name":"Correa (K4M) / Cadena (2.0/1.3T)","details":"K4M: correa c/60k","brands":"Gates, Continental","refs":[{"r":"Correa K4M c/60k","s":"confirmed"},{"r":"Cadena F4R/H5Ht","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"kit+distribucion+renault+megane"},{"t":"Amazon","u":AZ+"timing+belt+Renault+Megane"},{"t":"Gates","u":"https://www.gates.com/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"205/55 R16 / 225/45 R17","details":"","brands":"Michelin, Continental, Pirelli","refs":[{"r":"205/55 R16","s":"confirmed"},{"r":"225/45 R17","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+205+55+r16"},{"t":"Michelin","u":"https://www.michelin.cl/"},{"t":"Continental","u":"https://www.continental-neumaticos.cl/"}]}]}},
        "fiat_mobi":{"name":"Fiat Mobi 1.0 — 2017-2026","info":"Firefly 1.0 3cil | Cadena","crossNote":"Motor Firefly 1.0 comp. Argo 1.0, Cronos 1.0. Plataforma MSP","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-30","details":"API SN | ~3.0L","brands":"Selenia, Mobil, Shell","refs":[{"r":"5W-30 API SN","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w30+fiat"},{"t":"Amazon","u":AZ+"Selenia+5W-30"},{"t":"Selenia","u":"https://www.selenia.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite Firefly","details":"1.0 3cil","brands":"MANN, Tecfil, Mahle","refs":[{"r":"55282140 OEM (verificar)","s":"verify"},{"r":"MANN W 712/95 (verificar)","s":"verify"}],"interval":"c/10k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+fiat+mobi"},{"t":"Amazon","u":AZ+"oil+filter+Fiat+Mobi"},{"t":"MANN","u":"https://www.mann-filter.com/"}]}],"Encendido":[{"cat":"Bujias","name":"Bujias x3","details":"Firefly 3cil","brands":"NGK, Bosch","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/30k","links":[{"t":"MercadoLibre","u":ML+"bujia+fiat+mobi"},{"t":"Amazon","u":AZ+"spark+plug+Fiat+Mobi"},{"t":"NGK","u":"https://www.ngk.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"Disco solido ~240mm","brands":"TRW, Bosch, Cobreq","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/30-50k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+fiat+mobi"},{"t":"Amazon","u":AZ+"brake+pads+Fiat+Mobi"},{"t":"Bosch","u":"https://www.boschautoparts.com/"}]}],"Distribucion":[{"cat":"Cadena","name":"Cadena distribucion","details":"Firefly cadena","brands":"-","refs":[{"r":"Cadena Firefly","s":"confirmed"}],"interval":"Tensores c/100k+","links":[{"t":"MercadoLibre","u":ML+"cadena+distribucion+fiat+mobi"},{"t":"Amazon","u":AZ+"timing+chain+Fiat+Firefly"},{"t":"Fiat","u":"https://www.fiat.cl/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"175/65 R14 / 185/60 R15","details":"City car","brands":"Pirelli, Continental, Bridgestone","refs":[{"r":"175/65 R14","s":"confirmed"},{"r":"185/60 R15","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+175+65+r14"},{"t":"Pirelli","u":"https://www.pirelli.com/"},{"t":"Continental","u":"https://www.continental-neumaticos.cl/"}]}]}},
        "fiat_argo":{"name":"Fiat Argo 1.3/1.0/1.8 — 2018-2026","info":"Firefly 1.0/1.3 / E.torQ 1.8 | Cadena(Firefly)/Correa(1.8)","crossNote":"Firefly comp. Mobi/Cronos. E.torQ 1.8 comp. Toro","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-30","details":"API SN | 3.0-4.0L","brands":"Selenia, Mobil, Shell","refs":[{"r":"5W-30 API SN","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w30+fiat"},{"t":"Amazon","u":AZ+"Selenia+5W-30"},{"t":"Selenia","u":"https://www.selenia.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite","details":"Firefly/E.torQ","brands":"MANN, Tecfil, Mahle","refs":[{"r":"Verificar segun motor","s":"verify"}],"interval":"c/10k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+fiat+argo"},{"t":"Amazon","u":AZ+"oil+filter+Fiat+Argo"},{"t":"MANN","u":"https://www.mann-filter.com/"}]}],"Encendido":[{"cat":"Bujias","name":"Bujias x3/x4","details":"Segun motor","brands":"NGK, Bosch","refs":[{"r":"Verificar segun motor","s":"verify"}],"interval":"c/30k","links":[{"t":"MercadoLibre","u":ML+"bujia+fiat+argo"},{"t":"Amazon","u":AZ+"spark+plug+Fiat+Argo"},{"t":"NGK","u":"https://www.ngk.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"Disco ventilado ~257mm","brands":"TRW, Bosch, Cobreq","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/30-50k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+fiat+argo"},{"t":"Amazon","u":AZ+"brake+pads+Fiat+Argo"},{"t":"Bosch","u":"https://www.boschautoparts.com/"}]}],"Distribucion":[{"cat":"Cadena/Correa","name":"Cadena (Firefly) / Correa (E.torQ 1.8)","details":"1.8: correa c/50-60k","brands":"Gates, Continental","refs":[{"r":"Cadena Firefly","s":"confirmed"},{"r":"Correa E.torQ c/50-60k","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"distribucion+fiat+argo"},{"t":"Amazon","u":AZ+"timing+belt+Fiat+1.8"},{"t":"Gates","u":"https://www.gates.com/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"185/60 R15 / 195/55 R16","details":"","brands":"Pirelli, Continental, Bridgestone","refs":[{"r":"185/60 R15","s":"confirmed"},{"r":"195/55 R16","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+185+60+r15"},{"t":"Pirelli","u":"https://www.pirelli.com/"},{"t":"Continental","u":"https://www.continental-neumaticos.cl/"}]}]}},
        "fiat_cronos":{"name":"Fiat Cronos 1.3/1.8 — 2018-2026","info":"Firefly 1.3 / E.torQ 1.8 | Cadena(1.3)/Correa(1.8)","crossNote":"= Argo sedan. Motor Firefly comp. Mobi/Argo","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-30","details":"API SN | 3.0-4.0L","brands":"Selenia, Mobil, Shell","refs":[{"r":"5W-30 API SN","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w30+fiat"},{"t":"Amazon","u":AZ+"Selenia+5W-30"},{"t":"Selenia","u":"https://www.selenia.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite","details":"= Argo","brands":"MANN, Tecfil, Mahle","refs":[{"r":"Comp. Argo","s":"verify"}],"interval":"c/10k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+fiat+cronos"},{"t":"Amazon","u":AZ+"oil+filter+Fiat+Cronos"},{"t":"MANN","u":"https://www.mann-filter.com/"}]}],"Encendido":[{"cat":"Bujias","name":"Bujias x4","details":"Firefly/E.torQ","brands":"NGK, Bosch","refs":[{"r":"Comp. Argo","s":"verify"}],"interval":"c/30k","links":[{"t":"MercadoLibre","u":ML+"bujia+fiat+cronos"},{"t":"Amazon","u":AZ+"spark+plug+Fiat+Cronos"},{"t":"NGK","u":"https://www.ngk.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"= Argo","brands":"TRW, Bosch","refs":[{"r":"Comp. Argo","s":"verify"}],"interval":"c/30-50k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+fiat+cronos"},{"t":"Amazon","u":AZ+"brake+pads+Fiat+Cronos"},{"t":"Bosch","u":"https://www.boschautoparts.com/"}]}],"Distribucion":[{"cat":"Cadena/Correa","name":"Cadena (Firefly) / Correa (E.torQ)","details":"= Argo","brands":"Gates, Continental","refs":[{"r":"Cadena Firefly","s":"confirmed"},{"r":"Correa E.torQ c/50-60k","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"distribucion+fiat+cronos"},{"t":"Amazon","u":AZ+"timing+Fiat+Cronos"},{"t":"Gates","u":"https://www.gates.com/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"185/60 R15 / 195/55 R16","details":"Sedan","brands":"Pirelli, Continental, Bridgestone","refs":[{"r":"185/60 R15","s":"confirmed"},{"r":"195/55 R16","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+185+60+r15"},{"t":"Pirelli","u":"https://www.pirelli.com/"},{"t":"Continental","u":"https://www.continental-neumaticos.cl/"}]}]}},
        "fiat_pulse":{"name":"Fiat Pulse 1.0T/1.3 — 2022-2026","info":"Firefly 1.0T 3cil Turbo / 1.3 4cil | Cadena","crossNote":"Plataforma MLA. Motor 1.0T comp. Argo Turbo, Fastback","categories":{"Motor y Lubricacion":[{"cat":"Aceite","name":"Aceite 5W-30","details":"API SP | ~3.5L","brands":"Selenia, Mobil, Shell","refs":[{"r":"5W-30 API SP","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"aceite+5w30+fiat"},{"t":"Amazon","u":AZ+"Selenia+5W-30"},{"t":"Selenia","u":"https://www.selenia.com/"}]},{"cat":"Filtro Aceite","name":"Filtro aceite 1.0T/1.3","details":"Firefly turbo","brands":"MANN, Tecfil","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/10k","links":[{"t":"MercadoLibre","u":ML+"filtro+aceite+fiat+pulse"},{"t":"Amazon","u":AZ+"oil+filter+Fiat+Pulse"},{"t":"MANN","u":"https://www.mann-filter.com/"}]}],"Encendido":[{"cat":"Bujias","name":"Bujias x3 (1.0T) / x4 (1.3)","details":"Iridium turbo","brands":"NGK, Bosch","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/30-60k","links":[{"t":"MercadoLibre","u":ML+"bujia+fiat+pulse"},{"t":"Amazon","u":AZ+"spark+plug+Fiat+Pulse"},{"t":"NGK","u":"https://www.ngk.com/"}]}],"Frenos":[{"cat":"Pastillas Del.","name":"Pastillas delanteras","details":"Disco ventilado","brands":"TRW, Bosch","refs":[{"r":"Verificar OEM","s":"verify"}],"interval":"c/30-50k","links":[{"t":"MercadoLibre","u":ML+"pastillas+freno+fiat+pulse"},{"t":"Amazon","u":AZ+"brake+pads+Fiat+Pulse"},{"t":"TRW","u":"https://www.trwaftermarket.com/"}]}],"Distribucion":[{"cat":"Cadena","name":"Cadena distribucion","details":"Firefly turbo","brands":"-","refs":[{"r":"Cadena Firefly T","s":"confirmed"}],"interval":"Tensores c/100k+","links":[{"t":"MercadoLibre","u":ML+"cadena+distribucion+fiat+pulse"},{"t":"Amazon","u":AZ+"timing+chain+Fiat+Firefly+Turbo"},{"t":"Fiat","u":"https://www.fiat.cl/"}]}],"Neumaticos":[{"cat":"Neumatico","name":"195/60 R16 / 215/50 R17","details":"SUV compacto","brands":"Pirelli, Continental, Bridgestone","refs":[{"r":"195/60 R16","s":"confirmed"},{"r":"215/50 R17","s":"confirmed"}],"links":[{"t":"MercadoLibre","u":ML+"neumatico+195+60+r16"},{"t":"Pirelli","u":"https://www.pirelli.com/"},{"t":"Continental","u":"https://www.continental-neumaticos.cl/"}]}]}}
    }

    for vid, vdata in vehicles.items():
        c.execute("INSERT OR IGNORE INTO vehicles VALUES (?,?,?,?)", (vid, vdata["name"], vdata["info"], vdata["crossNote"]))
        order = 0
        for cat_name, parts in vdata["categories"].items():
            order += 1
            c.execute("INSERT INTO categories (vehicle_id, name, sort_order) VALUES (?,?,?)", (vid, cat_name, order))
            cat_id = c.lastrowid
            for p in parts:
                c.execute("INSERT INTO parts (category_id, cat_label, name, details, brands, interval_info) VALUES (?,?,?,?,?,?)",
                          (cat_id, p.get("cat",""), p["name"], p.get("details",""), p.get("brands",""), p.get("interval",None)))
                pid = c.lastrowid
                for r in p.get("refs",[]):
                    c.execute("INSERT INTO part_refs (part_id, reference, status) VALUES (?,?,?)", (pid, r["r"], r["s"]))
                for l in p.get("links",[]):
                    c.execute("INSERT INTO part_links (part_id, label, url) VALUES (?,?,?)", (pid, l["t"], l["u"]))
    conn.commit()
    total = c.execute("SELECT COUNT(*) FROM vehicles").fetchone()[0]
    parts_count = c.execute("SELECT COUNT(*) FROM parts").fetchone()[0]
    print(f"Bloque 15 insertado OK")
    print(f"Vehiculos totales: {total} | Componentes totales: {parts_count}")

if __name__ == "__main__":
    conn = sqlite3.connect(DB)
    conn.execute("PRAGMA foreign_keys = ON")
    ins(conn)
    conn.close()
